# Generated by Django 4.0.4 on 2022-06-14 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunaenvacunatorio',
            name='stock',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.CreateModel(
            name='listaDeEsperaFiebreAmarilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vacunation_app.paciente')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vacunation_app.vacuna')),
                ('vacunatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vacunation_app.vacunatorio')),
            ],
        ),
    ]
