# Generated by Django 4.0.4 on 2022-07-09 02:17

import Vacunation_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonregisteredvacunacion',
            name='dni',
            field=models.CharField(max_length=15, validators=[Vacunation_app.models.validate_decimal]),
        ),
    ]
