# Generated by Django 4.0.4 on 2022-07-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(choices=[('Gripe', 'Gripe'), ('COVID_PFIZER', 'Covid Pfizer'), ('COVID-Astrazeneca', 'Covid Astrazeneca'), ('Fiebre amarilla', 'Fiebre Amarilla')], max_length=100, unique=True),
        ),
    ]
