# Generated by Django 4.0.4 on 2022-05-29 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'permissions': [('Paciente', 'Correspondiente al rol de Paciente en la documentación')]},
        ),
    ]
