# Generated by Django 4.0.4 on 2022-05-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/profile_pic.png', upload_to='profile_images'),
        ),
    ]
