# Generated by Django 4.0.4 on 2022-05-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunatorio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
