# Generated by Django 4.0.4 on 2022-05-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0002_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='img/profile_pic.png', upload_to='profile_images'),
        ),
    ]
