# Generated by Django 4.0.4 on 2022-06-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0002_listadeesperacovid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dosis_covid',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two')]),
        ),
    ]
