# Generated by Django 3.2.5 on 2022-05-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0002_alter_usuario_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunador',
            name='user',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Vacunador',
        ),
    ]
