# Generated by Django 4.0.4 on 2022-05-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0002_alter_vacunatorio_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacunaenvacunatorio',
            unique_together={('vacunatorio', 'vacuna')},
        ),
    ]
