# Generated by Django 4.0.4 on 2022-05-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0003_alter_vacunaenvacunatorio_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacunaenvacunatorio',
            unique_together=set(),
        ),
    ]
