# Generated by Django 4.0.4 on 2022-05-31 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0003_alter_usuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='avatar',
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vacunation_app.paciente')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vacunation_app.vacuna')),
                ('vacunatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vacunation_app.vacunatorio')),
            ],
        ),
    ]
