# Generated by Django 4.0.4 on 2022-05-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0004_paciente_usuario_vacunador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(default='sada', max_length=4),
        ),
    ]
