# Generated by Django 3.2.5 on 2022-05-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0008_alter_vacuna_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(choices=[('FA', 'Fiebre amarilla'), ('GR', 'Gripe comun'), ('CPF', 'COVID-PFIEZER'), ('CAZ', 'COVID-Astrazeneca')], max_length=50),
        ),
    ]
