# Generated by Django 3.2.5 on 2022-05-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0014_alter_vacuna_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(choices=[('Covid-Z', 'COVID-Astrazeneca'), ('fiebreA', 'Fiebre amarilla'), ('Gripe', 'Gripe comun'), ('Covid-F', 'COVID-PFIEZER')], max_length=50, unique=True),
        ),
    ]
