# Generated by Django 3.2.5 on 2022-05-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacunation_app', '0015_alter_vacuna_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(choices=[('Covid-Z', 'COVID-Astrazeneca'), ('Gripe', 'Gripe comun'), ('Covid-F', 'COVID-PFIEZER'), ('fiebreA', 'Fiebre amarilla')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vacunatorio',
            name='nombre',
            field=models.CharField(choices=[('Plaza Moreno', 'Sede Plaza Moreno'), ('Gonnet', 'Sede Gonnet'), ('Omnibus', 'Sede Omnibus')], max_length=50),
        ),
    ]
